### ISSUE TITLE
Incorrect values in first chi-square test

### ISSUE THREAD

**Issue by JagaRamesh** [carmelhm/musclehub#1]
The following values are mentioned in the code:
contingency = [[250, 2259], [325, 2497]]
chi2, pval, dof, ex = chi2_contingency(contingency)

The correct values should be
contingency = [[250, 2259], [325, 2172]]
chi2, pval, dof, ex = chi2_contingency(contingency)
I see that you have taken the "total"(2497) instead of "No Application"(2172) for GroupB

**Comment by carmelhm** [comment]
Yeah I see it, you're right... It looks like the result is not very different anyway
